# Generated by Django 5.0.6 on 2024-05-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("S", "S")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="section",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("S", "S")],
                default="A",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
